server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/school?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 2









#git init
#git add README.md
#git commit -m "first commit"
#git branch -M main
#git remote add origin https://github.com/uch0731/Uncle.git
#git push -u origin main
#$ git config  user.name "Chang ho"
#$ git config  user.email uch0731@naver.com